name: CI/CD

on: [push, pull_request]
jobs:
  publish:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Build distribution
      run: |
        python -m pip install wheel
        python setup.py sdist bdist_wheel
    - name: Publish distribution
      uses: pypa/gh-action-pypi-publish@release/v1.4
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
